name: 🚀 Deploy Theme to cPanel

on:
  push:
    branches:
      - main  # Esto activa el deploy cada vez que subas cambios a la rama main

jobs:
  web-deploy:
    name: 🎉 Syncing Fastheme
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 🚀 FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        # ESTA ES TU RUTA EN GITHUB:
        local-dir: ./wordpress/wp-content/themes/fastheme/
        # ESTA ES TU RUTA EN EL SERVIDOR:
        server-dir: ./